#define SYSDEF_PATH
#include "cssysdef.h"
#include "cssys/sysdriv.h"
#include "csws/csws.h"
#include "version.h"
#include "ifontsrv.h"
#include "icfgnew.h"
#include "chimemenu.h"
#include "chimeBrowser.h"

class chimeBrowser;

// Scroll bar class default palette
HistoryWindow::~HistoryWindow() {}


HistoryWindow::HistoryWindow(csComponent *iParent)
  : csWindow(iParent, "-- History --", CSWS_TITLEBAR | CSWS_BUTCLOSE |
    CSWS_BUTMAXIMIZE)
  {

  InitCount();
  //SetState(CSS_SELECTABLE, true);

  SetRect (0, 15, app->bound.Width() / 4, app->bound.Height() / 3);
  SetState(CSS_DISABLED, true);

  int px = 15, py = 20;
  int labelw = 150;

  //////////create the dialog///////////////
  csDialog *d = new csDialog(this);
  this->SetDragStyle (this->GetDragStyle () & ~CS_DRAG_SIZEABLE);
  
  //////////create the list box/////////////
  lb = new csListBox (d, CSLBS_HSCROLL | CSLBS_VSCROLL, cslfsThinRect);
  lb->SetRect (bound.Width() / 10, bound.Height() / 5 - TitlebarHeight, bound.Width() / 10 * 9, bound.Height() / 5 * 4);

  //setup the "Go There"
  csButton *GoBut = new csButton(d, GO_THERE_PRESSED);
  GoBut->SetText("Go There");
  GoBut->SetSuggestedSize(.5 * (bound.Width() / 10 * 9 -  bound.Width() / 10), .5 * bound.Height() / 11);
  GoBut->SetPos(bound.Width() / 10, bound.Height() / 6 * 5);

}

//Add an item to the History Box
bool HistoryWindow::AddItem(char *item) {
	//char temp[50];
	//sprintf(temp, "%d. %s", ItemCount(), item);
	new csListBoxItem (lb, item, ItemCount());
	AddItem();
	return true;
}

//find a sector in the chime world
/*
bool HistoryWindow::FindSector(char *text) {

	for(int i = 0; i < history_list.Length(); i++)
	{
		HistoryItem* item = (HistoryItem*) history_list.Get(i);
		
		if(!strcmp(item->getItemName(), text)
			return item->getSector();		
	}

	else return -1;
}
*/

//Handle and Event generated by the History Window
bool HistoryWindow::HandleEvent (iEvent &Event)
{

  if (csWindow::HandleEvent (Event))
    return true;


  switch (Event.Type)
  {

    case csevCommand:

      switch (Event.Command.Code)
      {

		//if the user has selected a room to go to
		case cscmdListBoxItemSelected:
		case cscmdListBoxItemClicked:
		{
			csListBoxItem *srcItem = (csListBoxItem *) Event.Command.Info;
			strcpy(selected, srcItem->GetText());
		}
		return true;


	    //Go There button was pressed
        case GO_THERE_PRESSED:
			if (selected) {
				//int temp;
				//sscanf(selected, "%d. %s", &temp, selected);
				((chimeBrowser *)System)->TransportToRoom(selected);
			}
		return true;


		 //Cancel Button has been pressed
		case 66801:
		  Close();
		  return true;
	  }

      break;
  }

  return false;
}
